Asp.Net.Project.Yad2/Controllers/ProductController.cs
using Asp.Net.Project.Yad2.Services;
using Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net.Project.Yad2.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService ProductService;
        private readonly IUserService UserService;

        public ProductController(IProductService productService, IUserService userService)
        {
            ProductService = productService;
            UserService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NewProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewProduct(ProductModel product)
        {
            return View(product);
        }

        [HttpPost]
        public IActionResult AddProduct(ProductModel product, List<IFormFile> Images)
        {
            if (!ModelState.IsValid)
                return View("New_Product", product);

            for (int i = 0; i < Images.Count; i++)
            {
                if (Images[i].Length > 0)
                {
                    using MemoryStream ms = new MemoryStream();
                    Images[i].CopyTo(ms);
                    product.GetType().GetProperty($"Picture{i + 1}").SetValue(product, ms.ToArray());
                }
            }
            product.State = MyState.Available;
            string[] UsernamePassword = HttpContext.Request.Cookies["AspProjectCookie"].Split(',');
            product.Owner = product.User = UserService.GetUser(UsernamePassword[0], UsernamePassword[1]);
            product.Date = DateTime.Now;
            ProductService.Add(product);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult MoreDetails(long Id)
        {
            return View(ProductService.GetById(Id));
        }

        public IActionResult AddToCart(long id)
        {
            if (HttpContext.Request.Cookies.ContainsKey("AspProjectCookie"))
            {
                string[] UsernamePassword = HttpContext.Request.Cookies["AspProjectCookie"].Split(',');
                ProductService.AddProductToCart(id, UserService.GetUser(UsernamePassword[0], UsernamePassword[1]));
            }
            else if (HttpContext.Request.Cookies.ContainsKey("AspProjectGuestCart"))
                HttpContext.Response.Cookies.Append("AspProjectGuestCart", HttpContext.Request.Cookies["AspProjectGuestCart"] + $",{id}", new CookieOptions() { Expires = DateTime.Now.AddDays(7) });
            else
                HttpContext.Response.Cookies.Append("AspProjectGuestCart", $"{id}", new CookieOptions() { Expires = DateTime.Now.AddDays(7) });
            return RedirectToAction("Index", "Home");

        }

        public IActionResult RemoveFromCart(long id)
        {
            ProductService.RemoveFromCart(id);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Cart()
        {
            if (HttpContext.Request.Cookies.ContainsKey("AspProjectCookie"))
            {
                string[] UsernamePassword = HttpContext.Request.Cookies["AspProjectCookie"].Split(',');
                return View(ProductService.GetCart(UserService.GetUser(UsernamePassword[0], UsernamePassword[1])));
            }
            else
            {
                if (HttpContext.Request.Cookies.ContainsKey("AspProjectGuestCart"))
                {
                    List<long> ProductIDs = new List<long>();
                    HttpContext.Request.Cookies["AspProjectGuestCart"].Split(',').ToList().ForEach(idstring => ProductIDs.Add(long.Parse(idstring))); ;
                    return View(ProductService.GetCart(ProductIDs));
                }
                else
                {
                    return View(Enumerable.Empty<ProductModel>());
                }
            }
        }
        public IActionResult Buy()
        {
            if (HttpContext.Request.Cookies.ContainsKey("AspProjectCookie"))
            {
                string[] UsernamePassword = HttpContext.Request.Cookies["AspProjectCookie"].Split(',');
                ProductService.Buy((ProductService.GetCart(UserService.GetUser(UsernamePassword[0], UsernamePassword[1]))));
            }
            else
            {
                if (HttpContext.Request.Cookies.ContainsKey("AspProjectGuestCart"))
                {
                    List<long> ProductIDs = new List<long>();
                    HttpContext.Request.Cookies["AspProjectGuestCart"].Split(',').ToList().ForEach(idstring => ProductIDs.Add(long.Parse(idstring))); ;
                    ProductService.Buy((ProductService.GetCart(ProductIDs)));
                }
            }
            return RedirectToAction("Index", "Home");

        }

    }
}

Asp.Net.Project.Yad2/Controllers/UserController.cs
using Asp.Net.Project.Yad2.Models;
using Asp.Net.Project.Yad2.Services;
using Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net.Project.Yad2.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService UserService;
        public UserController(IUserService userService, IProductService productService)
        {
            UserService = userService;
        }

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(UserModel user)
        {
            if (!ModelState.IsValid)
                return View(user);
            if (UserService.IsExist(user.UserName))
            {
                TempData["User Exist"] = "correct";
                ViewBag.userExist = "User Exist";
                return View(user);
            }
            else
            {
                TempData["User Exist"] = "incorrect";
                UserService.Add(user);
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpPost]
        public IActionResult Login(SignIn user) //Checks if user exists, if not creates cookies
        {
            if (user == null)
            {
                TempData["LogInError"] = "Incorrect";
                return RedirectToAction("Index", "Home");
            }
            else if (UserService.IsUserNameAndPasswordExist(user.Username, user.SignInPassword))
            {
                TempData["LogInError"] = "Correct";
                HttpContext.Response.Cookies.Append("AspProjectCookie", $"{user.Username},{user.SignInPassword}", new CookieOptions() { Expires = (DateTime.Now).AddDays(3) });
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["LogInError"] = "Incorrect";
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public IActionResult UpdateUser()
        {
            UserModel user = HttpContext.Items["CookieKey"] as UserModel;
            if (user == null) return BadRequest();
            return View(user);
        }

        [HttpPost]
        public IActionResult UpdateUser(UserModel UpdatedUser)
        {
                UserService.Update(UpdatedUser);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult SignOut()
        {
            HttpContext.Response.Cookies.Delete("AspProjectCookie");
            return RedirectToAction("Index", "Home");
        }

    }
}

Asp.Net.Project.Yad2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Yad2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Yad2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @RenderSection("Title", required: false)
            </div>
        </nav>
    </header>
    <div class="container row">
        <div class="container col col-md-3 border-right">
            @await Html.PartialAsync("_PartialSideBar")
            @await Html.PartialAsync("_PartialNavigationBar")
        </div>
        <main role="main" class="pb-3 col container">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @RenderSection("Scripts", required: false)
</body>
</html>

Asp.Net.Project.Yad2/Views/Shared/_PartialLogIn.cshtml
@model SignIn

<div class="col-md-10 offset-md-1">
    <section>
        <form id="account" method="post" asp-controller="User" asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SignInPassword"></label>
                <input type="password" asp-for="SignInPassword" class="form-control" />
                <span asp-validation-for="SignInPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Log in</button>
                @if (TempData["LogInError"] as string == "Incorrect")
                {
                    <div class="text-danger">Incorrect Username or Password</div>}
            </div>
        </form>
    </section>
    <a asp-area="" asp-controller="User" asp-action="SignUp">Not a member? Register here!</a>
</div>

Asp.Net.Project.Yad2/Views/Shared/_PartialMainPage.cshtml
@model ProductModel
<link href="~/css/ImageSize.css" rel="stylesheet" />
@if (Model.State == MyState.Available)
{
    <div class="card d-inline-block" style="width: 18rem;">
        @if (Model.Picture1 != null)
        {
            <img src="data:image/png;base64,@Convert.ToBase64String(Model.Picture1)" class=" CustomeImage rounded img-fluid p-0" />}
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">
                <div>
                    @Model.ShortDescription
                </div>
                <div>
                    @Model.Price
                </div>
                <div>
                    @Model.State
                </div>
            </p>
            <a asp-action="MoreDetails" asp-controller="Product" asp-route-Id="@Model.Id">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info" viewBox="0 0 16 16">
                    <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                </svg>
            </a>
                <a asp-action="AddToCart" asp-controller="Product" asp-route-Id="@Model.Id">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                </a>

        </div>
    </div>
}

Asp.Net.Project.Yad2/Views/Shared/_PartialNavigationBar.cshtml
@{
    string a = (string)ViewData["Title"];
            }
@if (Context.Items.ContainsKey("CookieKey"))
{
    <div>
        <a class="@(a=="New Product"?"disabled":"") nav-link" asp-controller="Product" asp-action="NewProduct">NewProduct</a>
    </div>
}
<div>
    <a class="@(a=="Cart"?"disabled":"") nav-link" asp-action="Cart" asp-controller="product"> Cart </a>
</div>
<div>
    
    <a class="@(a=="Home Page"?"disabled":"")  nav-link" asp-controller="Home" asp-action="Index">Home Page</a>
</div>
<div>
    <a class="@(a=="Privacy Policy"?"disabled":"") nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

Asp.Net.Project.Yad2/Views/Shared/_PartialSideBar.cshtml
@if (!Context.Items.ContainsKey("CookieKey")) //If user is signed in
{
    @await Html.PartialAsync("_PartialLogIn", new SignIn()) }
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><h2 class="navbar-text">@Greeting() @(((UserModel)Context.Items["CookieKey"]).UserName)!</h2></li>

</ul>

<a asp-area="" asp-controller="User" asp-action="UpdateUser">Want to update account details? Update here!</a>

<br />

<a asp-area="" asp-controller="User" asp-action="SignOut">Log out</a>

<br />
}

@{string Greeting() //Greeting function to determine time of day
    {
        if (int.Parse(DateTime.Now.ToString("HH")) > 12)
        {
            if (int.Parse(DateTime.Now.ToString("HH")) > 19)
            {
                return "Good Evening";
            }
            return "Good Afternoon";
        }
        else
        {
            return "Good Morning";
        }
    }}

@section Scripts {
    <partial name="General/_ValidationScriptsPartial" />
}